# Generated by Django 6.0.3 on 2026-03-24 23:51

import datetime
import django.core.validators
import django.db.models.deletion
import judge.validators.validadores_de_data
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.IntegerField(default=20, help_text='Peso', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da categoria', max_length=50, validators=[django.core.validators.MinLengthValidator(5)])),
                ('slug', models.SlugField(help_text='Slug da categoria', unique=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('descricao', models.TextField(blank=True, help_text='Descrição da categoria', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Competicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da competição', max_length=200, validators=[django.core.validators.MinLengthValidator(5)])),
                ('slug', models.SlugField(help_text='Slug da Competição', unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('descricao', models.TextField(help_text='Descrição da Competição', validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(1000)])),
                ('url', models.URLField(blank=True, help_text='URL da competição', max_length=500, null=True)),
                ('inicio', models.DateTimeField(help_text='Data de início')),
                ('termino', models.DateTimeField(help_text='Data de Término')),
                ('freeze', models.DateTimeField(help_text='Data do Freeze')),
                ('publico', models.BooleanField(default=True)),
                ('criado', models.DateTimeField(default=datetime.datetime.now, help_text='Data de início')),
                ('atualizado', models.DateTimeField(default=datetime.datetime.now, help_text='Data de atualização')),
                ('penalidade', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Exemplo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField(help_text='Ordem', unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Linguagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome da linguagem', max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('slug', models.SlugField(help_text='Slug da Linguagem', validators=[django.core.validators.MinLengthValidator(3)])),
                ('compilador', models.CharField(help_text='Compilador', max_length=80, validators=[django.core.validators.MinLengthValidator(5)])),
                ('versao', models.CharField(help_text='Versão', max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('multiplicador_tempo', models.FloatField(help_text='Multiplicador do tempo', validators=[django.core.validators.MinValueValidator(1.0)])),
                ('multiplicador_memoria', models.FloatField(help_text='Multiplicador da Memória', validators=[django.core.validators.MinValueValidator(1.0)])),
                ('ativo', models.BooleanField(default=True, help_text='Ativo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Participacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro', models.DateTimeField(help_text='Registro')),
                ('oficial', models.BooleanField(default=True, help_text='Oficial')),
                ('total_pontos', models.IntegerField(help_text='Total de Pontos', validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Problema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(help_text='Código', max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(4)])),
                ('titulo', models.CharField(help_text='Título', max_length=200, unique=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('enunciado', models.TextField(help_text='Enunciado', max_length=5000, unique=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('enunciado_entrada', models.TextField(help_text='Enunciado de entrada', max_length=2000, unique=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('enunciado_saida', models.TextField(help_text='Enunciado de Saída', max_length=2000, unique=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('dificuldade', models.CharField(choices=[('1', 'Muito Fácil'), ('2', 'Fácil'), ('3', 'Básico'), ('4', 'intermediário'), ('5', 'Intermediário Alto'), ('6', 'Difícil'), ('7', 'Muito Difícil'), ('8', 'Avançado'), ('9', 'Muito Avançado'), ('10', 'Perito')])),
                ('idioma', models.CharField(choices=[('Português do Brasil', 'Pt Br'), ('Inglês dos EUA', 'En Us'), ('Espanhol da Espanha', 'Es Es')])),
                ('fonte', models.CharField(help_text='Fonte', max_length=150, validators=[django.core.validators.MinLengthValidator(3)])),
                ('limite_tempo', models.CharField(choices=[('1000', '1 segundo'), ('2000', '2 segundos'), ('3000', '3 segundos'), ('4000', '4 segundos'), ('5000', '5 segundos'), ('6000', '6 segundos'), ('7000', '7 segundos'), ('8000', '8 segundos'), ('9000', '9 segundos'), ('10000', '10 segundo')])),
                ('limite_memoria', models.CharField(choices=[('8 MB', '8 MB'), ('16 MB', '16 MB'), ('32 MB', '32 MB'), ('64 MB', '64 MB'), ('128 MB', '128 MB'), ('256 MB', '256 MB')])),
                ('publico', models.BooleanField(default=True)),
                ('nota', models.CharField(choices=[('100', 'Nota1'), ('150', 'Nota2'), ('200', 'Nota3'), ('250', 'Nota4'), ('300', 'Nota5'), ('400', 'Nota6'), ('500', 'Nota7'), ('600', 'Nota8'), ('800', 'Nota9'), ('1000', 'Nota10')])),
                ('criado', models.DateTimeField(default=datetime.datetime.now, help_text='Data de criação')),
                ('atualizacao', models.DateTimeField(default=datetime.datetime.now, help_text='Data de Atualização')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProblemaCompeticao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Label do Problema', max_length=5, validators=[django.core.validators.MinLengthValidator(1)])),
                ('pontos', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('ordem', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Submissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linguagem', models.CharField(help_text='Linguagem do Código', max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('codigo_fonte', models.CharField(help_text='Código Fonte', max_length=1000, validators=[django.core.validators.MinLengthValidator(1)])),
                ('status', models.CharField(choices=[('Não Respondida', 'Not Answered'), ('Em fila de Execução', 'In Queue'), ('Execução', 'Running'), ('Aceito', 'Accepted'), ('resposta Errada', 'Wrong Answer'), ('Tempo Limite Excedido', 'Time Limit Exceeded'), ('Limite de memória Excedido', 'Memory Limit Exceeded'), ('Erro de Runtime', 'Runtime Error'), ('Erro de Compilação', 'Compilation Error'), (' Erro de Apresentação', 'Presentation Error'), ('Erro Interno', 'Internal Error')], help_text='Status Atual')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do Teste', max_length=80, validators=[django.core.validators.MinLengthValidator(5)])),
                ('dados_entrada', models.TextField(help_text='Dados de Entrada', validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(5000)])),
                ('dados_saida', models.TextField(help_text='Dados de Saída', validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(5000)])),
                ('criado', models.DateTimeField(default=datetime.datetime.now)),
                ('atualizado', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_nascimento', models.DateField(help_text='Data de Nascimento', validators=[judge.validators.validadores_de_data.data_minima])),
                ('pais', models.CharField(help_text='País de origem', max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('genero', models.CharField(choices=[('Homem', 'Man'), ('Mulher', 'Woman'), ('Não Binário', 'Non Binary'), ('Não informado', 'Not Informed')])),
                ('pagina_pessoal', models.URLField(blank=True, help_text='URL do perfil', max_length=150, null=True, validators=[django.core.validators.MinLengthValidator(15)])),
                ('biografia', models.TextField(blank=True, help_text='Biografia', null=True)),
                ('idioma', models.CharField(choices=[('Português do Brasil', 'Pt Br'), ('Inglês dos EUA', 'En Us'), ('Espanhol da Espanha', 'Es Es')], help_text='Idioma')),
                ('premium', models.BooleanField(default=False, help_text='Perfil Premium')),
                ('membro_desde', models.DateField(default=datetime.date.today, help_text='Tempo como membro')),
                ('instituicao', models.CharField(help_text='Instituição', max_length=120, validators=[django.core.validators.MinLengthValidator(3)])),
                ('posicao_ranking', models.IntegerField(help_text='Posição no Ranking', validators=[django.core.validators.MinValueValidator(1)])),
                ('resolvidos', models.IntegerField(default=0, help_text='Quantidade de Problemas Resolvidos', validators=[django.core.validators.MinValueValidator(0)])),
                ('submetidos', models.IntegerField(default=0, help_text='Quantidade de Problemas Submetidos', validators=[django.core.validators.MinValueValidator(0)])),
                ('treinador', models.BooleanField(default=False, help_text='Perfil com Treinador')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
