# Generated by Django 6.0.3 on 2026-03-25 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problema',
            name='categoria',
            field=models.ManyToManyField(help_text='Selecione uma categoria para o problema', to='judge.categoria'),
        ),
    ]
