# Generated by Django 6.0.3 on 2026-03-25 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0002_problema_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='competicao',
            name='perfil',
            field=models.ManyToManyField(help_text='Selecione os perfis relacionados com a competição', to='judge.perfil'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='participacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='judge.participacao'),
        ),
        migrations.AddField(
            model_name='problema',
            name='linguagem',
            field=models.ManyToManyField(help_text='Selecione a linguagem atribuída ao Problema', to='judge.linguagem'),
        ),
        migrations.AddField(
            model_name='problema',
            name='perfil',
            field=models.ManyToManyField(help_text='Selecione o perfil atribuído ao Problema', to='judge.perfil'),
        ),
        migrations.AddField(
            model_name='problema',
            name='submissao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='judge.submissao'),
        ),
        migrations.AddField(
            model_name='problemacompeticao',
            name='competicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='judge.competicao'),
        ),
        migrations.AddField(
            model_name='problemacompeticao',
            name='problema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='judge.problema'),
        ),
        migrations.AddField(
            model_name='teste',
            name='problema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='judge.problema'),
        ),
        migrations.AlterField(
            model_name='submissao',
            name='linguagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.linguagem'),
        ),
    ]
