# Generated by Django 5.2.5 on 2026-04-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='magazines',
            field=models.ManyToManyField(blank=True, null=True, through='aula.Publication', through_fields=('paper', 'magazine'), to='aula.magazine'),
        ),
    ]
