# Generated by Django 6.0.2 on 2026-03-03 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('area', models.CharField(blank=True, max_length=20, null=True)),
                ('instituicao', models.CharField(default='ifrs', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('sigla', models.CharField(blank=True, max_length=4, null=True)),
                ('instituicao', models.CharField(default='IFRS', max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
