# Generated by Django 6.0.2 on 2026-02-27 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemplo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='area',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
