# Generated by Django 6.0.2 on 2026-03-03 01:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemplo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=7)),
                ('quantidade', models.IntegerField()),
                ('peso', models.FloatField()),
                ('descricao', models.TextField()),
                ('cliente', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='categoria',
            name='area',
            field=models.CharField(blank=True, help_text='Informe a área do conhecimento segundo o padrão CAPES', max_length=20, null=True, verbose_name='Área do conhecimento'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='instituicao',
            field=models.CharField(default='ifrs', help_text='Máximo de 10 caracteres', max_length=10, verbose_name='Instituição'),
        ),
    ]
