# Generated by Django 6.0.2 on 2026-02-27 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemplo', '0002_categoria_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='instituicao',
            field=models.CharField(default='ifrs', max_length=10),
        ),
    ]
