# Generated by Django 6.0.2 on 2026-02-27 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemplo', '0003_categoria_instituicao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('sigla', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
