# Generated by Django 6.0.2 on 2026-02-27 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemplo', '0004_disciplinas'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinas',
            name='intituicao',
            field=models.CharField(default='IFRS', max_length=3),
        ),
        migrations.AlterField(
            model_name='disciplinas',
            name='nome',
            field=models.CharField(max_length=30),
        ),
    ]
