# Generated by Django 6.0.2 on 2026-02-27 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exemplo', '0005_disciplinas_intituicao_alter_disciplinas_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disciplinas',
            old_name='intituicao',
            new_name='instituicao',
        ),
    ]
