# Generated by Django 6.0.2 on 2026-02-27 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemplo', '0006_rename_intituicao_disciplinas_instituicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinas',
            name='sigla',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
