# Generated by Django 6.0.2 on 2026-02-27 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemplo', '0007_alter_disciplinas_sigla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinas',
            name='instituicao',
            field=models.CharField(default='IFRS', max_length=15),
        ),
    ]
