# Generated by Django 6.0.2 on 2026-02-27 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exemplo', '0008_alter_disciplinas_instituicao'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Disciplinas',
            new_name='Disciplina',
        ),
    ]
