# Generated by Django 5.2.5 on 2026-04-02 18:14

import django.core.validators
import wrapper.validators.memoria_validador
import wrapper.validators.palavras_proibidas
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.IntegerField(help_text='Código do problema', unique=True, validators=[django.core.validators.MinValueValidator(1000)])),
                ('titulo', models.CharField(help_text='Título do problema', max_length=100, validators=[django.core.validators.MinLengthValidator(3), wrapper.validators.palavras_proibidas.PalavrasProibidas(lista_proibida=['teste', 'admin'], mensagem='O campo contém palavras que foram proibidas. Ex: teste; admin.')], verbose_name='Título')),
                ('nivel', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1, help_text='Escolha o nível do problema', verbose_name='Nível')),
                ('descricao', models.TextField(help_text='Insira a descrição doproblema para o usuário', max_length=2000, validators=[django.core.validators.MinLengthValidator(20), wrapper.validators.palavras_proibidas.PalavrasProibidas(lista_proibida=['irã', 'trump', 'eua'], mensagem='Você utilizou palavras proibidas. Revise as diretrizes das questões.')], verbose_name='Descrição')),
                ('exemplo_entrada', models.TextField(help_text='Entrada para a solução do probblema', max_length=2000, verbose_name='Exemplo de entrada')),
                ('exemplo_saida', models.TextField(help_text='Saída esperada para a solução do probblema', max_length=2000, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Exemplo de saída')),
                ('testes_entrada', models.TextField(help_text='Entrada para a solução do probblema', max_length=2000, verbose_name='Entrada')),
                ('testes_saida', models.TextField(help_text='Saída esperada para a solução do probblema', max_length=2000, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Saída esperada')),
                ('pontuacao', models.FloatField(help_text='Insira a pontuação a ser creditada para o usuário', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Pontuação')),
                ('tempo_execucao', models.IntegerField(help_text='Insira ao tempo máximo de execução', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Tempo de execução do programa')),
                ('memoria_maxima', models.IntegerField(help_text='Informe a quantidade em MB de memória máxima a ser utilizada', validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(256), wrapper.validators.memoria_validador.validar_tamanho_memoria], verbose_name='Memória máxima')),
                ('resolvidos', models.IntegerField(default=0, help_text='Quantidade de usuários que resolveram o problema', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Resolvidos')),
            ],
            options={
                'verbose_name': 'Problema de Computação',
                'verbose_name_plural': 'Problemas de Computação',
                'ordering': ['-titulo', 'cod'],
                'unique_together': {('titulo', 'nivel')},
            },
        ),
    ]
