# Generated by Django 5.2.5 on 2026-04-02 18:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('area', models.CharField(blank=True, help_text='Informe a área do conhecimentosegundo o padrão CAPES.', max_length=20, null=True, verbose_name='Área do conhecimento')),
                ('instituicao', models.CharField(default='IFRS', help_text='Digite a instituição, com no máximo 10 caracteres.', max_length=10, verbose_name='Instituição')),
                ('teste', models.CharField(default='-', max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome para a cidade', max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('estado', models.CharField(help_text='Insira a sigla do estado', max_length=2, validators=[django.core.validators.MinLengthValidator(2)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Esporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome para o esporte', max_length=20, validators=[django.core.validators.MinLengthValidator(4)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome para o time', max_length=20, validators=[django.core.validators.MinLengthValidator(3)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da Pessoa', max_length=40, validators=[django.core.validators.MinLengthValidator(3)])),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], help_text='Selecione o sexo da pessoa', max_length=1, validators=[django.core.validators.MinLengthValidator(1)])),
                ('idade', models.IntegerField(help_text='Insira a idade da pessoa', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('renda', models.DecimalField(decimal_places=2, help_text='Insira a renda da pessoa', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('cidade', models.ForeignKey(help_text='Selecione a cidade que mora', on_delete=django.db.models.deletion.RESTRICT, to='wrapper.cidade')),
                ('esporte_favorito', models.ForeignKey(help_text='Selecione o esporte favorito', on_delete=django.db.models.deletion.RESTRICT, to='wrapper.esporte')),
                ('time_torce', models.ForeignKey(help_text='Selecione o time que torce', on_delete=django.db.models.deletion.RESTRICT, to='wrapper.time')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
