# Generated by Django 6.0.3 on 2026-03-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('area', models.CharField(blank=True, help_text='Digite a área do conhecimento segundo o padrão CAPES', max_length=20, null=True, verbose_name='Área do conhecimento')),
                ('instituicao', models.CharField(default='IFRS', help_text='Digite a sigla da instituição de ensino (no máximo 5 caracteres)', max_length=5, verbose_name='Instutuição de ensino')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
