# Generated by Django 6.0.3 on 2026-03-10 21:02

import appUm.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUm', '0002_alter_categoria_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Digite o nome do aluno.', max_length=50, verbose_name='Nome')),
                ('ano_nascimento', models.DateField(help_text='Digite a data de nascimento do aluno.', verbose_name='Data de Nascimento')),
                ('cpf', models.CharField(help_text='Digite o CPF do aluno', max_length=11, validators=[appUm.validators.cpf], verbose_name='CPF')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
