# Generated by Django 6.0.3 on 2026-03-10 21:04

import appUm.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUm', '0003_aluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(help_text='Digite o CPF do aluno', max_length=14, validators=[appUm.validators.cpf], verbose_name='CPF'),
        ),
    ]
