# Generated by Django 6.0.3 on 2026-03-13 01:00

import datetime
import django.core.validators
import django.db.models.deletion
import relacionamento.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo da pessoa', max_length=100, validators=[django.core.validators.MinLengthValidator(5)])),
                ('data_nascimento', models.DateField(help_text='Selecione a data de nascimento', verbose_name='Idade da pessoa')),
                ('cpf', models.CharField(help_text='CPF da pessoa', max_length=11, unique=True, validators=[relacionamento.validators.validacao_cpf], verbose_name='CPF')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relacionamento.pessoa')),
                ('email', models.EmailField(help_text='Email institucional', max_length=100, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Email')),
            ],
            options={
                'abstract': False,
            },
            bases=('relacionamento.pessoa',),
        ),
        migrations.CreateModel(
            name='Passaporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Número do passaporte da pessoa', max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Número do Passaporte')),
                ('emissao', models.DateField(help_text='Data de emissão do passaporte', validators=[django.core.validators.MinValueValidator(datetime.date.today)], verbose_name='Data de Emissão')),
                ('vencimento', models.DateField(help_text='Data de vencimento do passaporte', verbose_name='Data de Vencimento')),
                ('pessoa', models.OneToOneField(help_text='Selecione o titular do passaporte', on_delete=django.db.models.deletion.PROTECT, to='relacionamento.pessoa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título do artigo', max_length=255, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Título')),
                ('data_publicacao', models.DateField(help_text='Data de publicação do artigo', validators=[django.core.validators.MinValueValidator(datetime.date.today)], verbose_name='Data de Publicação')),
                ('autor', models.ForeignKey(help_text='Selecione o autor do artigo', on_delete=django.db.models.deletion.PROTECT, to='relacionamento.reporter', verbose_name='Reporter Autor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
