# Generated by Django 6.0.3 on 2026-03-27 01:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacionamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome para a cidade', max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('estado', models.CharField(help_text='Sigla para o estado', max_length=2, validators=[django.core.validators.MinLengthValidator(2)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Esporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome para o esporte', max_length=20, validators=[django.core.validators.MinLengthValidator(4)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome para o time', max_length=20, validators=[django.core.validators.MinLengthValidator(3)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pessoaa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da pessoa', max_length=40, validators=[django.core.validators.MinLengthValidator(3)])),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], help_text='Sexo da pessoa', max_length=1, validators=[django.core.validators.MinLengthValidator(1)])),
                ('idade', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('renda', models.DecimalField(decimal_places=1, help_text='Insira a renda da pessoa', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('cidade', models.ForeignKey(help_text='Seleciona a cidade', on_delete=django.db.models.deletion.CASCADE, to='relacionamento.cidade')),
                ('esporte_favotiro', models.ForeignKey(help_text='Selecione o seu esporte de torcida', on_delete=django.db.models.deletion.RESTRICT, to='relacionamento.esporte')),
                ('time_torce', models.ForeignKey(help_text='Selecione o seu time de torcida', on_delete=django.db.models.deletion.RESTRICT, to='relacionamento.time')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
