# Generated by Django 6.0.3 on 2026-03-13 01:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacionamento', '0002_revista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revista',
            name='edicao',
            field=models.IntegerField(help_text='Número da edição da revista', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Edição da Revista'),
        ),
    ]
