# Generated by Django 6.0.3 on 2026-03-13 01:22

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacionamento', '0003_alter_revista_edicao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reportagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título da reportagem', max_length=200, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Título')),
                ('data_publicacao', models.DateField(help_text='Data de publicação da reportagem', validators=[django.core.validators.MinValueValidator(datetime.date.today), django.core.validators.MaxValueValidator(datetime.date.today)], verbose_name='Data de Publicação')),
                ('revistas', models.ManyToManyField(help_text='Selecione as revistas relacionadas a reportagem', to='relacionamento.revista')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
