# Generated by Django 6.0.3 on 2026-03-12 22:33

import categoria.validators.memory_validator
import categoria.validators.palavras_proibidas
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(help_text='Código do problema', unique=True, validators=[django.core.validators.MinValueValidator(1000), categoria.validators.palavras_proibidas.PalavrasProibidas(lista_proibida=['teste', 'admin'], mensagem='o campo contem palavras que foram proibidas')])),
                ('titulo', models.CharField(help_text='Titulo do problema', max_length=100, validators=[django.core.validators.MinValueValidator(3)], verbose_name='Titulo')),
                ('nivel', models.IntegerField(choices=[(1, 'Um'), (2, 'Dois'), (3, 'Tres'), (4, 'Quatro'), (5, 'Cinco'), (6, 'Seis'), (7, 'Sete'), (8, 'Oito'), (9, 'Nove'), (10, 'Dez')], default=1, help_text='Escolha o nivel do problema', verbose_name='Nivel')),
                ('descricao', models.TextField(help_text='Insira a descricao do problema para o usuario', max_length=2000, validators=[django.core.validators.MinLengthValidator(20)], verbose_name='descricao')),
                ('exemplo_entrada', models.TextField(help_text='Entrada esperada para a solucao do problema', max_length=2000, verbose_name='exemplo de entrada')),
                ('exemplo_saida', models.TextField(help_text='Saida esperada para a solucao do problema', max_length=2000, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='exemplo saida')),
                ('testes_entrada', models.TextField(help_text='teste esperado para a solucao do problema', max_length=2000, verbose_name='teste de entrada')),
                ('testes_saida', models.TextField(help_text='teste esperado para a solucao do problema', max_length=2000, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='teste saida')),
                ('pontuacao', models.FloatField(help_text='Insira a pontuacao a ser creditada para o usuario', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='pontuacao')),
                ('tempo_execucao', models.IntegerField(help_text='Insira o tempo maximo de execucao', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='tempo execucao')),
                ('memoria_maxima', models.IntegerField(help_text='Insira a quantidade em MB de memoria maxima a ser utilizada', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(256), categoria.validators.memory_validator.validar_tamanho_memoria], verbose_name='memoria maxima')),
                ('resolvidos', models.IntegerField(help_text='quantidade de usuarios que resolveram o problema', validators=[django.core.validators.MinValueValidator(0)], verbose_name='resolvidos')),
            ],
        ),
        migrations.DeleteModel(
            name='teste',
        ),
    ]
